"""WAF 检测与指纹识别模块。"""

import re

# ──────────────────────────────────────────────
# WAF 指纹库
# ──────────────────────────────────────────────
WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": {"server": "cloudflare", "cf-ray": ""},
        "cookies": {"__cfduid": ""},
        "body": [r"cloudflare-nginx", r"cf-ray", r"__cfduid"],
    },
    "ModSecurity": {
        "headers": {"server": "mod_security|modsecurity"},
        "cookies": {},
        "body": [r"ModSecurity", r"mod_security"],
    },
    "AWS WAF": {
        "headers": {"x-amzn-requestid": "", "x-amzn-trace-id": ""},
        "cookies": {"aws-waf-token": ""},
        "body": [r"Request blocked", r"AWS WAF"],
    },
    "F5 BIG-IP ASM": {
        "headers": {"x-wa-info": "", "x-asm-version": "", "x-asm-policy": ""},
        "cookies": {"TS": "", "LastMRH_Session": ""},
        "body": [r"The requested URL was rejected", r"TS[0-9a-f]{6}"],
    },
    "Akamai": {
        "headers": {"x-akamai-transformed": ""},
        "cookies": {"ak_bmsc": ""},
        "body": [r"akamai", r"reference #[0-9a-f]{16}"],
    },
    "Imperva Incapsula": {
        "headers": {"x-iinfo": ""},
        "cookies": {"incap_ses": "", "visid_incap": ""},
        "body": [r"Incapsula", r"_Incapsula_Resource"],
    },
    "Sucuri": {
        "headers": {"x-sucuri-id": "", "x-sucuri-cache": ""},
        "cookies": {},
        "body": [r"Sucuri", r"sucuri.net"],
    },
    "Barracuda": {
        "headers": {"x-barracuda": ""},
        "cookies": {},
        "body": [r"Barracuda"],
    },
    "Fortinet FortiWeb": {
        "headers": {"x-fw-server": ""},
        "cookies": {"FORTIWAFSID": ""},
        "body": [r"FortiWeb", r"fgd_icon"],
    },
    "Microsoft Azure WAF": {
        "headers": {"x-ms-request-id": ""},
        "cookies": {},
        "body": [r"Azure WAF", r"Microsoft-Azure-Application-Gateway"],
    },
    "Cisco ACE XML Gateway": {
        "headers": {"x-cisco-ace": ""},
        "cookies": {},
        "body": [],
    },
    "Alibaba Cloud WAF": {
        "headers": {"x-slb-instance-id": ""},
        "cookies": {},
        "body": [r"waf.alibaba", r"Aliyun WAF"],
    },
    "SafeDog": {
        "headers": {"wzws-ray": "", "x-powered-by": "WZWS"},
        "cookies": {},
        "body": [r"SafeDog", r"safedog"],
    },
    "DDoS-Guard": {
        "headers": {"x-ddos-guard": ""},
        "cookies": {"ddos_guard": ""},
        "body": [],
    },
    "Wordfence": {
        "headers": {},
        "cookies": {"wfvt_": ""},
        "body": [r"Wordfence", r"Generated by Wordfence"],
    },
    "Tencent Cloud WAF": {
        "headers": {"x-nws-log-uuid": ""},
        "cookies": {"waf_": ""},
        "body": [r"tencent.*waf", r"腾讯云.*防火墙"],
    },
    "Huawei Cloud WAF": {
        "headers": {"x-hw-waf": ""},
        "cookies": {},
        "body": [r"huawei.*waf", r"华为.*防火墙"],
    },
    "Qianxin WAF": {
        "headers": {"x-qianxin-waf": ""},
        "cookies": {},
        "body": [r"qianxin", r"奇安信", r"天守"],
    },
    "NSFOCUS WAF": {
        "headers": {"x-nsfocus-waf": ""},
        "cookies": {},
        "body": [r"nsfocus", r"绿盟"],
    },
    "Hillstone WAF": {
        "headers": {"x-hillstone": ""},
        "cookies": {},
        "body": [r"hillstone", r"山石"],
    },
    "DBAppSecurity (安恒)": {
        "headers": {"x-dbapp-waf": ""},
        "cookies": {},
        "body": [r"dbapp", r"安恒", r"明御"],
    },
    "Venustech (启明星辰)": {
        "headers": {},
        "cookies": {"venustech": ""},
        "body": [r"venustech", r"启明星辰"],
    },
    "TopSec (天融信)": {
        "headers": {"x-topsec": ""},
        "cookies": {},
        "body": [r"topsec", r"天融信"],
    },
    "Volcengine WAF (火山引擎)": {
        "headers": {"x-volc-waf": ""},
        "cookies": {},
        "body": [r"volcengine", r"火山引擎"],
    },
    "Jiasule (加速乐)": {
        "headers": {"x-jsl-uid": ""},
        "cookies": {"__jsluid": "", "__jsl_clearance": ""},
        "body": [r"jiasule", r"加速乐"],
    },
    "Yundun (云盾)": {
        "headers": {"x-yundun": ""},
        "cookies": {"yundun": ""},
        "body": [r"yundun", r"云盾"],
    },
    "Baidu Cloud WAF": {
        "headers": {"x-bce-waf": ""},
        "cookies": {},
        "body": [r"baidu.*waf", r"百度云"],
    },
    "Reblaze": {
        "headers": {"x-reblaze": ""},
        "cookies": {"rbzid": ""},
        "body": [r"reblaze"],
    },
    "Wallarm": {
        "headers": {"x-wallarm": ""},
        "cookies": {},
        "body": [r"wallarm"],
    },
    "Signal Sciences": {
        "headers": {"x-sigsci": ""},
        "cookies": {"__sigsci": ""},
        "body": [r"signal.*sciences"],
    },
    "PerimeterX": {
        "headers": {"x-px": ""},
        "cookies": {"_pxhd": ""},
        "body": [r"perimeterx", r"px-captcha"],
    },
    "DataDome": {
        "headers": {"x-datadome": ""},
        "cookies": {"datadome": ""},
        "body": [r"datadome", r"dd\.js"],
    },
    "Kasada": {
        "headers": {"x-kpsdk": ""},
        "cookies": {},
        "body": [r"kasada", r"149e9513"],
    },
    "Grey Wizard": {
        "headers": {"gw-server": ""},
        "cookies": {},
        "body": [r"grey.*wizard"],
    },
    "Zscaler": {
        "headers": {"x-zscaler": ""},
        "cookies": {},
        "body": [r"zscaler"],
    },
}

# ──────────────────────────────────────────────
# 通用拦截检测
# ──────────────────────────────────────────────
BLOCK_KEYWORDS = [
    "waf", "firewall", "forbidden", "blocked", "denied", "deny",
    "access denied", "access denied.", "access is denied",
    "not allowed", "request blocked", "request rejected",
    "malicious", "suspicious", "attack detected",
    "security policy", "security violation", "violation",
    "illegal characters", "invalid input",
    "mod_security", "modsecurity",
    "your request has been blocked",
    "has been blocked by",
    "bad request", "invalid request",
    "the requested url was rejected",
    "please try again later",
    "cannot be processed",
    "our systems have detected",
    "automated requests are not allowed",
]

BLOCK_STATUS_CODES = {
    403, 406, 501, 503, 429, 444, 493, 494, 495,
}


# ──────────────────────────────────────────────
# Functions
# ──────────────────────────────────────────────

def identify_waf(headers, body_text, status_code):
    """Try to identify which WAF is deployed based on response.

    Returns list of (name, confidence) tuples.
    """
    matches = []
    for name, sig in WAF_SIGNATURES.items():
        score = 0
        total = 0

        for header, pattern in sig["headers"].items():
            total += 1
            val = headers.get(header, "")
            if val:
                if pattern:
                    if re.search(pattern, val, re.I):
                        score += 1
                else:
                    score += 1

        for cookie, pattern in sig["cookies"].items():
            total += 1
            raw = headers.get("set-cookie", "")
            if raw and cookie in raw:
                if pattern:
                    if re.search(pattern, raw, re.I):
                        score += 1
                else:
                    score += 1

        for body_pat in sig["body"]:
            total += 1
            if re.search(body_pat, body_text, re.I):
                score += 1

        if total > 0 and score > 0:
            confidence = score / total
            matches.append((name, round(confidence, 2)))

    matches.sort(key=lambda x: -x[1])
    return matches


def is_blocked(response):
    """Determine whether the WAF blocked the request."""
    text = response.text.lower()

    # Status code check
    if response.status_code in BLOCK_STATUS_CODES:
        return True

    # Keyword check
    for kw in BLOCK_KEYWORDS:
        if kw in text:
            return True

    # Response length anomaly
    # (if response is very short / generic, it's likely a block page)
    if response.status_code != 200 and len(text) < 500:
        return True

    return False


def block_reason(response):
    """Return a short string describing why a request was blocked."""
    if response.status_code in (403,):
        return f"HTTP {response.status_code} Forbidden"
    if response.status_code == 406:
        return "HTTP 406 Not Acceptable"
    if response.status_code == 429:
        return "HTTP 429 Rate Limited"
    if response.status_code in (503, 493, 494, 495):
        return f"HTTP {response.status_code}"
    if response.status_code == 501:
        return "HTTP 501 Not Implemented"

    text = response.text.lower()
    for kw in BLOCK_KEYWORDS:
        if kw in text:
            return kw[:50]

    return f"HTTP {response.status_code} (short page)"
